$pdf_mode = 5;
$xelatex = 'xelatex -shell-escape -interaction-nonstopmode %O %S';

$pdf_previewer = 'start sioyek %O %S';
$preview_continuous_mode = 1;

@default_files = ('algebraIV.tex');

$biber = 'biber %O %S';

$recorder = 1;
$clean_ext = 'synctex.gz synctex.gz(busy) nav snm vrb run.xml bbl blg xdv';

$regenerate_after_file_change = 1;
